apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 172.17.0.201
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: backend
  sessionAffinity: None
  type: LoadBalancer
