apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T07:28:10Z"
  labels:
    app: suber
  name: suber
  namespace: default
  resourceVersion: "2541"
  selfLink: /api/v1/namespaces/default/services/suber
  uid: 2d3f250b-1ae6-4937-9b3c-4fcaa0e1205f
spec:
  clusterIP: 10.103.164.229
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: suber
  sessionAffinity: None
  type: ClusterIP
